### ISSUE TITLE
Cannot run on Arm

### ISSUE THREAD

**Issue by ngelotte** [Daddoon/Blazor.Polyfill#61]
I am trying to run the blazor Polyfill on .net 5 in a docker container on a Raspberry Pi.  But it just crashes below is the app starting up and then one initial request. 

Is there a way to maybe generate the javascript in VS and then package it with the app as libChakraCore.so is not available for Arm?

`Name or service not known
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://[::]:80
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /app
Name or service not known
Name or service not known
Name or service not known
Name or service not known
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
      React.Exceptions.BabelException: Unable to resolve type: React.ReactEnvironment
       ---> React.TinyIoC.TinyIoCResolutionException: Unable to resolve type: React.ReactEnvironment
       ---> React.TinyIoC.TinyIoCResolutionException: Unable to resolve type: React.JavaScriptEngineFactory
       ---> JavaScriptEngineSwitcher.Core.JsEngineLoadException: Failed to create instance of the ChakraCoreJsEngine. Most likely it happened, because the 'libChakraCore.so' assembly or one of its dependencies was not found. There is no JavaScriptEngineSwitcher.ChakraCore.Native.linux-* package for the arm processor architecture. You can build the 'libChakraCore.so' assembly for the current processor architecture by using following instructions from official repository - https://github.com/Microsoft/ChakraCore/wiki/Building-ChakraCore#linux.

      Engine name: ChakraCoreJsEngine
      Engine version: 1.11.24
      Category: Engine load error
      Description: Most likely it happened, because the 'libChakraCore.so' assembly or one of its dependencies was not found. There is no JavaScriptEngineSwitcher.ChakraCore.Native.linux-* package for the arm processor architecture. You can build the 'libChakraCore.so' assembly for the current processor architecture by using following instructions from official repository - https://github.com/Microsoft/ChakraCore/wiki/Building-ChakraCore#linux. ---> System.DllNotFoundException: Unable to load shared library 'ChakraCore' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libChakraCore: cannot open shared object file: No such file or directory
         at JavaScriptEngineSwitcher.ChakraCore.JsRt.NativeMethods.JsCreateRuntime(JsRuntimeAttributes attributes, JsThreadServiceCallback threadService, JsRuntime& runtime)
         at JavaScriptEngineSwitcher.ChakraCore.JsRt.JsRuntime.Create(JsRuntimeAttributes attributes, JsThreadServiceCallback threadServiceCallback)
         at JavaScriptEngineSwitcher.ChakraCore.ChakraCoreJsEngine.<>c__DisplayClass10_0.<.ctor>b__0()
         at JavaScriptEngineSwitcher.ChakraCore.ScriptDispatcher.ScriptTaskWithoutResult.Run()
      --- End of stack trace from previous location ---
         at JavaScriptEngineSwitcher.ChakraCore.ScriptDispatcher.Invoke(Action action)
         at JavaScriptEngineSwitcher.ChakraCore.ChakraCoreJsEngine..ctor(ChakraCoreSettings settings)
         at JavaScriptEngineSwitcher.ChakraCore.ChakraCoreJsEngine..ctor(ChakraCoreSettings settings)
         at JavaScriptEngineSwitcher.ChakraCore.ChakraCoreJsEngineFactory.CreateEngine()
         at JSPool.JsPool`2.CreateEngine()
         at JSPool.JsPool`2.PopulateEngines()
         at JSPool.JsPool`2..ctor(JsPoolConfig`1 config)
         at JSPool.JsPool..ctor(JsPoolConfig config)
         at React.JavaScriptEngineFactory.CreatePool()
         at React.JavaScriptEngineFactory..ctor(IJsEngineSwitcher jsEngineSwitcher, IReactSiteConfiguration config, ICache cache, IFileSystem fileSystem)
         at lambda_method52(Closure , Object[] )
         at React.TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)

         --- End of inner exception stack trace ---
         at React.TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
         at React.TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, ResolveOptions options)
         at React.TinyIoC.TinyIoCContainer.SingletonFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options)
         at React.TinyIoC.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options)
         at React.TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
         --- End of inner exception stack trace ---
         at React.TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
         at React.TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, ResolveOptions options)
         at React.TinyIoC.TinyIoCContainer.CustomObjectLifetimeFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options)
         at React.TinyIoC.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options)
         at React.TinyIoC.TinyIoCContainer.Resolve(Type resolveType)
         at React.TinyIoC.TinyIoCContainer.Resolve[ResolveType]()
         at Blazor.Polyfill.Server.BlazorPolyfillMiddlewareExtensions.Transform(String input, String filename, String babelrcJSON)
         --- End of inner exception stack trace ---
         at Blazor.Polyfill.Server.BlazorPolyfillMiddlewareExtensions.Transform(String input, String filename, String babelrcJSON)
         at Blazor.Polyfill.Server.BlazorPolyfillMiddlewareExtensions.GetPatchedBlazorServerFile()
         at Blazor.Polyfill.Server.BlazorPolyfillMiddlewareExtensions.CacheBlazorPolyfillLib()
         at Blazor.Polyfill.Server.BlazorPolyfillMiddlewareExtensions.<>c.<UseBlazorPolyfill>b__7_0(HttpContext context, Func`1 next)
         at Microsoft.AspNetCore.Builder.UseExtensions.<>c__DisplayClass0_1.<Use>b__1(HttpContext context)
         at React.AspNet.BabelFileMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
Name or service not known
Name or service not known
Name or service not known
Name or service not known
Name or service not known
Name or service not known
Name or service not known
Name or service not known
Name or service not known
Name or service not known
Name or service not known
Name or service not known
Name or service not known
Name or service not known
Name or service not known
Name or service not known
`

**Comment by Daddoon** [comment]
After some reading it seem that Chakracore does not support ARM under Linux, but is fine over Windows ARM.

V8 was used previously but was problematic because it requires some recent dependencies of GLIBC that may not be installed on Azure images of Linux (I suspect Debian under the hood).

Same issue for Debian 10 stock installation.

In the end it seem V8 does support ARM globally . The V8 Engine is also shipped in dependencies of this project. However even after switching, you may have issue if you don’t install the required GLIBC dependency on your system or Docker image. You will see what is required in the errors by the way.

Can you try to change the default engine by:

- Removing the AddBlazorPolyfill call from Startup.cs 
- Write the same piece of code in source but replace the default engine by V8:

```csharp

            services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();
            services.AddReact();

            services.AddJsEngineSwitcher(options => options.DefaultEngineName = V8JsEngine.EngineName)
                .AddChakraCore()
                .AddV8();
```

Maybe I will do some kind of documentation or update for this case.
But can you confirm this workaround your issue ?

**Comment by ngelotte** [comment]
I set it up to not use ChakraCore but V8 errors out as well. Here is what I get. It is missing a the .so file for arm. I just copied the 2 js files from my machine running Visual Studio and then removed all the code to blazorpolyfill and it is basically working now. 

Here is the error.

Name or service not known
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://[::]:80
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /app
Name or service not known
Name or service not known
Name or service not known
Name or service not known
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
      React.Exceptions.BabelException: Unable to resolve type: React.ReactEnvironment
       ---> React.TinyIoC.TinyIoCResolutionException: Unable to resolve type: React.ReactEnvironment
       ---> React.TinyIoC.TinyIoCResolutionException: Unable to resolve type: React.JavaScriptEngineFactory
       ---> JavaScriptEngineSwitcher.Core.JsEngineLoadException: Failed to create instance of the ChakraCoreJsEngine. Most likely it happened, because the 'libChakraCore.so' assembly or one of its dependencies was not found. There is no JavaScriptEngineSwitcher.ChakraCore.Native.linux-* package for the arm processor architecture. You can build the 'libChakraCore.so' assembly for the current processor architecture by using following instructions from official repository - https://github.com/Microsoft/ChakraCore/wiki/Building-ChakraCore#linux.

      Engine name: ChakraCoreJsEngine
      Engine version: 1.11.24
      Category: Engine load error
      Description: Most likely it happened, because the 'libChakraCore.so' assembly or one of its dependencies was not found. There is no JavaScriptEngineSwitcher.ChakraCore.Native.linux-* package for the arm processor architecture. You can build the 'libChakraCore.so' assembly for the current processor architecture by using following instructions from official repository - https://github.com/Microsoft/ChakraCore/wiki/Building-ChakraCore#linux. ---> System.DllNotFoundException: Unable to load shared library 'ChakraCore' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libChakraCore: cannot open shared object file: No such file or directory
         at JavaScriptEngineSwitcher.ChakraCore.JsRt.NativeMethods.JsCreateRuntime(JsRuntimeAttributes attributes, JsThreadServiceCallback threadService, JsRuntime& runtime)
         at JavaScriptEngineSwitcher.ChakraCore.JsRt.JsRuntime.Create(JsRuntimeAttributes attributes, JsThreadServiceCallback threadServiceCallback)
         at JavaScriptEngineSwitcher.ChakraCore.ChakraCoreJsEngine.<>c__DisplayClass10_0.<.ctor>b__0()
         at JavaScriptEngineSwitcher.ChakraCore.ScriptDispatcher.ScriptTaskWithoutResult.Run()
      --- End of stack trace from previous location ---
         at JavaScriptEngineSwitcher.ChakraCore.ScriptDispatcher.Invoke(Action action)
         at JavaScriptEngineSwitcher.ChakraCore.ChakraCoreJsEngine..ctor(ChakraCoreSettings settings)
         at JavaScriptEngineSwitcher.ChakraCore.ChakraCoreJsEngine..ctor(ChakraCoreSettings settings)
         at JavaScriptEngineSwitcher.ChakraCore.ChakraCoreJsEngineFactory.CreateEngine()
         at JSPool.JsPool`2.CreateEngine()
         at JSPool.JsPool`2.PopulateEngines()
         at JSPool.JsPool`2..ctor(JsPoolConfig`1 config)
         at JSPool.JsPool..ctor(JsPoolConfig config)
         at React.JavaScriptEngineFactory.CreatePool()
         at React.JavaScriptEngineFactory..ctor(IJsEngineSwitcher jsEngineSwitcher, IReactSiteConfiguration config, ICache cache, IFileSystem fileSystem)
         at lambda_method52(Closure , Object[] )
         at React.TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)

         --- End of inner exception stack trace ---
         at React.TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
         at React.TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, ResolveOptions options)
         at React.TinyIoC.TinyIoCContainer.SingletonFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options)
         at React.TinyIoC.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options)
         at React.TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
         --- End of inner exception stack trace ---
         at React.TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
         at React.TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, ResolveOptions options)
         at React.TinyIoC.TinyIoCContainer.CustomObjectLifetimeFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options)
         at React.TinyIoC.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options)
         at React.TinyIoC.TinyIoCContainer.Resolve(Type resolveType)
         at React.TinyIoC.TinyIoCContainer.Resolve[ResolveType]()
         at Blazor.Polyfill.Server.BlazorPolyfillMiddlewareExtensions.Transform(String input, String filename, String babelrcJSON)
         --- End of inner exception stack trace ---
         at Blazor.Polyfill.Server.BlazorPolyfillMiddlewareExtensions.Transform(String input, String filename, String babelrcJSON)
         at Blazor.Polyfill.Server.BlazorPolyfillMiddlewareExtensions.GetPatchedBlazorServerFile()
         at Blazor.Polyfill.Server.BlazorPolyfillMiddlewareExtensions.CacheBlazorPolyfillLib()
         at Blazor.Polyfill.Server.BlazorPolyfillMiddlewareExtensions.<>c.<UseBlazorPolyfill>b__7_0(HttpContext context, Func`1 next)
         at Microsoft.AspNetCore.Builder.UseExtensions.<>c__DisplayClass0_1.<Use>b__1(HttpContext context)
         at React.AspNet.BabelFileMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
Name or service not known
Name or service not known
Name or service not known
Name or service not known
Name or service not known
Name or service not known
Name or service not known
Name or service not known
Name or service not known
Name or service not known
Name or service not known
Name or service not known
Name or service not known
Name or service not known
Name or service not known
Name or service not known
Name or service not known
Name or service not known
Name or service not known
Name or service not known
Name or service not known
Name or service not known
Name or service not known
Name or service not known
^Cinfo: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
pi@raspberrypi:~ $ docker pull ghcr.io/ngelotte/tinkerbutton/tinker-button-blazor-image-arm:latest
latest: Pulling from ngelotte/tinkerbutton/tinker-button-blazor-image-arm
be493c6a5984: Already exists
45a8fb606ce6: Pull complete
0f2a4477341a: Pull complete
431ce52db233: Pull complete
62224ba6f0e4: Pull complete
beca28ab2068: Pull complete
e9e0b0a193d2: Pull complete
Digest: sha256:751342ad55792878ec31b3c07ba628002041ef42265825c8efc87cee1d70fd04
Status: Downloaded newer image for ghcr.io/ngelotte/tinkerbutton/tinker-button-blazor-image-arm:latest
ghcr.io/ngelotte/tinkerbutton/tinker-button-blazor-image-arm:latest
pi@raspberrypi:~ $ docker run -it -p 80:80 --name blazor --rm --env MosquittoAddress=mosquitto --network tinker --mount source=blazor-data,target=/data ghcr.io/ngelotte/tinkerbutton/tinker-button-blazor-image-arm:latest
warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
      Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {8a15788a-c31d-4033-b97d-3965b5701bdd} may be persisted to storage in unencrypted form.
Name or service not known
Name or service not known
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://[::]:80
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /app
Name or service not known
Name or service not known
Name or service not known
Name or service not known
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
      React.Exceptions.BabelException: Unable to resolve type: React.ReactEnvironment
       ---> React.TinyIoC.TinyIoCResolutionException: Unable to resolve type: React.ReactEnvironment
       ---> React.TinyIoC.TinyIoCResolutionException: Unable to resolve type: React.JavaScriptEngineFactory
       ---> JavaScriptEngineSwitcher.Core.JsEngineLoadException: Failed to create instance of the V8JsEngine. Most likely it happened, because the 'ClearScriptV8.linux-arm.so' assembly or one of its dependencies was not found. See the original error message: “Cannot load ClearScript V8 library. Load failure information for ClearScriptV8.linux-arm.so:
      /app/runtimes/linux-arm/native/ClearScriptV8.linux-arm.so: Unable to load shared library '/app/runtimes/linux-arm/native/ClearScriptV8.linux-arm.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: /app/runtimes/linux-arm/native/ClearScriptV8.linux-arm.so: cannot open shared object file: No such file or directory
      /app/ClearScriptV8.linux-arm.so: Unable to load shared library '/app/ClearScriptV8.linux-arm.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: /app/ClearScriptV8.linux-arm.so: cannot open shared object file: No such file or directory
      ClearScriptV8.linux-arm.so: Unable to load shared library 'ClearScriptV8.linux-arm.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: ClearScriptV8.linux-arm.so: cannot open shared object file: No such file or directory”.

      Engine name: V8JsEngine
      Engine version: 8.7.220.25
      Category: Engine load error
      Description: Most likely it happened, because the 'ClearScriptV8.linux-arm.so' assembly or one of its dependencies was not found. See the original error message: “Cannot load ClearScript V8 library. Load failure information for ClearScriptV8.linux-arm.so:
      /app/runtimes/linux-arm/native/ClearScriptV8.linux-arm.so: Unable to load shared library '/app/runtimes/linux-arm/native/ClearScriptV8.linux-arm.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: /app/runtimes/linux-arm/native/ClearScriptV8.linux-arm.so: cannot open shared object file: No such file or directory
      /app/ClearScriptV8.linux-arm.so: Unable to load shared library '/app/ClearScriptV8.linux-arm.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: /app/ClearScriptV8.linux-arm.so: cannot open shared object file: No such file or directory
      ClearScriptV8.linux-arm.so: Unable to load shared library 'ClearScriptV8.linux-arm.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: ClearScriptV8.linux-arm.so: cannot open shared object file: No such file or directory”. ---> System.TypeLoadException: Cannot load ClearScript V8 library. Load failure information for ClearScriptV8.linux-arm.so:
      /app/runtimes/linux-arm/native/ClearScriptV8.linux-arm.so: Unable to load shared library '/app/runtimes/linux-arm/native/ClearScriptV8.linux-arm.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: /app/runtimes/linux-arm/native/ClearScriptV8.linux-arm.so: cannot open shared object file: No such file or directory
      /app/ClearScriptV8.linux-arm.so: Unable to load shared library '/app/ClearScriptV8.linux-arm.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: /app/ClearScriptV8.linux-arm.so: cannot open shared object file: No such file or directory
      ClearScriptV8.linux-arm.so: Unable to load shared library 'ClearScriptV8.linux-arm.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: ClearScriptV8.linux-arm.so: cannot open shared object file: No such file or directory
         at Microsoft.ClearScript.V8.V8Proxy.LoadNativeLibrary(String baseName, String platform, String architecture, String extension)
         at Microsoft.ClearScript.V8.V8Proxy.LoadNativeAssembly()
         at Microsoft.ClearScript.V8.V8Proxy.OnEntityHolderCreated()
         at Microsoft.ClearScript.V8.SplitProxy.V8EntityHolder..ctor(String name, Func`1 acquireHandle)
         at Microsoft.ClearScript.V8.SplitProxy.V8IsolateProxyImpl..ctor(String name, V8RuntimeConstraints constraints, V8RuntimeFlags flags, Int32 debugPort)
         at Microsoft.ClearScript.V8.V8IsolateProxy.Create(String name, V8RuntimeConstraints constraints, V8RuntimeFlags flags, Int32 debugPort)
         at Microsoft.ClearScript.V8.V8Runtime..ctor(String name, V8RuntimeConstraints constraints, V8RuntimeFlags flags, Int32 debugPort)
         at Microsoft.ClearScript.V8.V8Runtime..ctor(String name, V8RuntimeConstraints constraints, V8RuntimeFlags flags)
         at Microsoft.ClearScript.V8.V8Runtime..ctor(String name, V8RuntimeConstraints constraints)
         at Microsoft.ClearScript.V8.V8ScriptEngine..ctor(V8Runtime runtime, String name, V8RuntimeConstraints constraints, V8ScriptEngineFlags flags, Int32 debugPort)
         at Microsoft.ClearScript.V8.V8ScriptEngine..ctor(String name, V8RuntimeConstraints constraints, V8ScriptEngineFlags flags, Int32 debugPort)
         at Microsoft.ClearScript.V8.V8ScriptEngine..ctor(V8RuntimeConstraints constraints, V8ScriptEngineFlags flags, Int32 debugPort)
         at JavaScriptEngineSwitcher.V8.V8JsEngine..ctor(V8Settings settings)
         at JavaScriptEngineSwitcher.V8.V8JsEngine..ctor(V8Settings settings)
         at JavaScriptEngineSwitcher.V8.V8JsEngineFactory.CreateEngine()
         at JSPool.JsPool`2.CreateEngine()
         at JSPool.JsPool`2.PopulateEngines()
         at JSPool.JsPool`2..ctor(JsPoolConfig`1 config)
         at JSPool.JsPool..ctor(JsPoolConfig config)
         at React.JavaScriptEngineFactory.CreatePool()
         at React.JavaScriptEngineFactory..ctor(IJsEngineSwitcher jsEngineSwitcher, IReactSiteConfiguration config, ICache cache, IFileSystem fileSystem)
         at lambda_method52(Closure , Object[] )
         at React.TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)

         --- End of inner exception stack trace ---
         at React.TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
         at React.TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, ResolveOptions options)
         at React.TinyIoC.TinyIoCContainer.SingletonFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options)
         at React.TinyIoC.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options)
         at React.TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
         --- End of inner exception stack trace ---
         at React.TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
         at React.TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, ResolveOptions options)
         at React.TinyIoC.TinyIoCContainer.CustomObjectLifetimeFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options)
         at React.TinyIoC.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options)
         at React.TinyIoC.TinyIoCContainer.Resolve(Type resolveType)
         at React.TinyIoC.TinyIoCContainer.Resolve[ResolveType]()
         at Blazor.Polyfill.Server.BlazorPolyfillMiddlewareExtensions.Transform(String input, String filename, String babelrcJSON)
         --- End of inner exception stack trace ---
         at Blazor.Polyfill.Server.BlazorPolyfillMiddlewareExtensions.Transform(String input, String filename, String babelrcJSON)
         at Blazor.Polyfill.Server.BlazorPolyfillMiddlewareExtensions.GetPatchedBlazorServerFile()
         at Blazor.Polyfill.Server.BlazorPolyfillMiddlewareExtensions.CacheBlazorPolyfillLib()
         at Blazor.Polyfill.Server.BlazorPolyfillMiddlewareExtensions.<>c.<UseBlazorPolyfill>b__7_0(HttpContext context, Func`1 next)
         at Microsoft.AspNetCore.Builder.UseExtensions.<>c__DisplayClass0_1.<Use>b__1(HttpContext context)
         at React.AspNet.BabelFileMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
Name or service not known
Name or service not known
Name or service not known

**Comment by Daddoon** [comment]
Seems that the ARM64 bit are missing on my build, the support has been made just 9 days ago ! 

I must update ClearScript dependencies and the Native images included by default.

I will take a look tomorrow. What docker image type are you using if I want to test ?

Wishing that it will be sufficient, as I fear the GLIBCXXX 3.4.26 library missing eventually on default Docker images.

**Comment by ngelotte** [comment]
I am using the following docker images
Base image:
mcr.microsoft.com/dotnet/aspnet:5.0.2-buster-slim-arm32v7
SDK image
mcr.microsoft.com/dotnet/sdk:5.0.102-ca-patch-buster-slim

There is a docker bug with the main SDK image at the moment. So that is why I am using the ca patch. https://github.com/NuGet/Announcements/issues/49

**Comment by Daddoon** [comment]
I see that you are using an ARM32v7 image.
There is no support for this with the Js Engines to transpile.

I will try to add a packaged version of the transpiled and fixed version of Blazor server js file in the next release for this kind of scenario, even if it’s less ideal. This package should try to avoid using a specific version of a library, that’s why transpilation was used dynamically.

i will keep you updated soon, maybe tomorrow or just after.

**Comment by ngelotte** [comment]
Ok. That would be great. I know that 32bit arm is a limiting factor for using some of the .net packages. Thanks for being willing to help.

**Comment by Daddoon** [comment]
Done !

See the [OS & CPU Compatibilities](https://github.com/Daddoon/Blazor.Polyfill/blob/master/README.md#os--cpu-compatibilities) section i have written.
Keep me updated if this is working.

**Comment by Daddoon** [comment]
Ho, and of course, update your NuGet package to the last version here. See:

https://www.nuget.org/packages/BlazorPolyfill.Server/5.0.102

**Comment by ngelotte** [comment]
Tried out the latest package and it work great on my Raspberry Pi now. Thanks for all your help.

**Comment by Daddoon** [comment]
Great ! Thanks for the feedback !
