### ISSUE TITLE
Problems with IJSRuntime.InvokeVoidAsync

### ISSUE THREAD

**Issue by ngelotte** [Daddoon/Blazor.Polyfill#62]
I am using InvokeVoidAsync on a windows machine in IE 11 to call a javascript method that is in _host. It works on chrome  but in IE 11 with the Polyfill setup in startup.cs I get the below error in the c# code. I am not using BlazorPolyfill.Build as I don't need module support so it did not seem relevant.

The javascript is 
`
        window.PlayAudioFile = (src) => {
            var sound = document.createElement('audio');
            sound.src = src;
            sound.type = 'audio/mpeg';
            document.body.appendChild(sound);
            sound.load();
            sound.play();
        }
`
I call it with `await js.InvokeVoidAsync("PlayAudioFile", fullFileName);`

----Error ---
Microsoft.JSInterop.JSException
  HResult=0x80131500
  Message=Could not find 'PlayAudioFile' ('PlayAudioFile' was undefined).
Error: Could not find 'PlayAudioFile' ('PlayAudioFile' was undefined).
   at Anonymous function (http://localhost:55722/_framework/blazor.server.js:1:69862)
   at Anonymous function (http://localhost:55722/_framework/blazor.polyfill.min.js:1:4449)
   at Anonymous function (http://localhost:55722/_framework/blazor.polyfill.min.js:1:55749)
   at n.prototype.findFunction (http://localhost:55722/_framework/blazor.server.js:1:69796)
   at l (http://localhost:55722/_framework/blazor.server.js:1:69234)
   at Anonymous function (http://localhost:55722/_framework/blazor.server.js:1:71228)
   at B (http://localhost:55722/_framework/blazor.polyfill.min.js:1:89252)
   at n.jsCallDispatcher.beginInvokeJSFromDotNet (http://localhost:55722/_framework/blazor.server.js:1:71198)
   at Anonymous function (http://localhost:55722/_framework/blazor.server.js:1:27300)
   at Anonymous function (http://localhost:55722/_framework/blazor.polyfill.min.js:1:4449)
  Source=System.Private.CoreLib
  StackTrace:
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__15`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Microsoft.JSInterop.JSRuntimeExtensions.<InvokeVoidAsync>d__0.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TinkerButtonBlazor.Pages.ReactionME.<PlayAudio>d__11.MoveNext() in C:\Users\ngelotte\source\repos\TinkerButton\TinkerButtonBlazor\Pages\ReactionME.razor:line 48

**Comment by Daddoon** [comment]
IE11 does not support lambda expression. That‘s why you must be careful when writing code, or use BlazorPolyfill.Build or Babel by yourself to transpile ES6/ES2015 syntax to ES5. 

IE11 only support ES5. In the meantime, being carefully about your writing try this instead:

```js
window.PlayAudioFile = function (src)
{
   var sound = document.createElement('audio');
   sound.src = src;
   sound.type = 'audio/mpeg';
   document.body.appendChild(sound);
   sound.load();
   sound.play(); 
}
```

**Comment by ngelotte** [comment]
Thanks. I have gotten so used to using lambdas I forgot that it was a ES6 function. Switching it to a standard function fixed that error message.

**Comment by Daddoon** [comment]
Great !
