### ISSUE TITLE
Please update for .NET 6

### ISSUE THREAD

**Issue by SpeednetGroup** [Daddoon/Blazor.Polyfill#68]
Unfortunately it looks like the polyfill does not work after upgrading a project to .NET 6.

The error messages when trying to run under .NET 6 are:

```
React.Exceptions.BabelException: Error: /blazor.server.js: Expected atom at position 3
    ^\s*Blazor-Co
       ^
   at a (React.Core.Resources.babel.generated.min.js:1:1608241) -> …tion(e){var t={};function r(n){if(t[n])return t[n].exports;var a=t[n]={i:n,l:!1,exports:{}};return e
 ---> JavaScriptEngineSwitcher.Core.JsRuntimeException: Error: /blazor.server.js: Expected atom at position 3
    ^\s*Blazor-Co
       ^
   at a (React.Core.Resources.babel.generated.min.js:1:1608241) -> …tion(e){var t={};function r(n){if(t[n])return t[n].exports;var a=t[n]={i:n,l:!1,exports:{}};return e

Engine name: ChakraCoreJsEngine
Engine version: 1.11.24
Category: Runtime error
Description: /blazor.server.js: Expected atom at position 3
    ^\s*Blazor-Co
       ^
Type: Error
Document name: React.Core.Resources.babel.generated.min.js
Line number: 1
Column number: 1608241
Source fragment: …tion(e){var t={};function r(n){if(t[n])return t[n].exports;var a=t[n]={i:n,l:!1,exports:{}};return e
Call stack:
   at a (React.Core.Resources.babel.generated.min.js:1:1608241) ---> JavaScriptEngineSwitcher.ChakraCore.JsRt.JsScriptException: Script threw an exception.
   at JavaScriptEngineSwitcher.ChakraCore.JsRt.JsErrorHelpers.ThrowIfError(JsErrorCode errorCode)
   at JavaScriptEngineSwitcher.ChakraCore.JsRt.JsValue.CallFunction(JsValue[] arguments)
   at JavaScriptEngineSwitcher.ChakraCore.ChakraCoreJsEngine.<>c__DisplayClass27_0.<InnerCallFunction>b__0()
   at React.ReactEnvironment.ExecuteWithBabel[T](String function, Object[] args)
   at Blazor.Polyfill.Server.BlazorPolyfillMiddlewareExtensions.Transform(String input, String filename, String babelrcJSON)

   --- End of inner exception stack trace ---
   at Blazor.Polyfill.Server.BlazorPolyfillMiddlewareExtensions.Transform(String input, String filename, String babelrcJSON)
   at Blazor.Polyfill.Server.BlazorPolyfillMiddlewareExtensions.GetPatchedBlazorServerFile()
   at Blazor.Polyfill.Server.BlazorPolyfillMiddlewareExtensions.CacheBlazorPolyfillLib()
   at Blazor.Polyfill.Server.BlazorPolyfillMiddlewareExtensions.<>c.<UseBlazorPolyfill>b__10_0(HttpContext context, Func`1 next)
   at Microsoft.AspNetCore.Builder.UseExtensions.<>c__DisplayClass0_1.<Use>b__1(HttpContext context)
   at React.AspNet.BabelFileMiddleware.Invoke(HttpContext context)
   at LotteryPost.StatusCodeExceptionHandler.InvokeAsync(HttpContext context) in C:\Development\Web Project\Lottery Post\Lottery Post\Class\StatusCodeException.cs:line 29
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.WebTools.BrowserLink.Net.BrowserLinkMiddleware.ExecuteWithFilterAsync(IHttpSocketAdapter injectScriptSocket, String requestId, HttpContext httpContext)
   at Microsoft.AspNetCore.Watch.BrowserRefresh.BrowserRefreshMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()
```

**Comment by Daddoon** [comment]
Started to try to develop a fix on this branch: https://github.com/Daddoon/Blazor.Polyfill/tree/dev_issue_68_support_net6
However it still doesn't work as expected.

- Navigation does reload the page totally
- Submitting a FileInput seems to return an arrayBuffer not supported exception
- However events on the already loaded page seems to work.

I don't know yet where to look for why the navigation behavior does not work like before.

**Comment by Daddoon** [comment]
An update has been release !
You can find it on NuGet: https://www.nuget.org/packages/BlazorPolyfill.Server/

Just a little note, i don't know if it's a change due to the polyfills and how Blazor is managed, but at least while using it on IE11, a little delay in order to the page to be fully loaded / synced seems to be needed in order to have everything working as expected, otherwise, the navigation management as a SPA does not work.

I hope this will be sufficient. Otherwise, maybe i will have to find a workaround in order to get Blazor.Server to "wait" for full sync on IE11.

**Comment by SpeednetGroup** [comment]
Thank you for working on this!  I updated from NuGet, and it looks like IE is throwing two errors on each page.  

```
SCRIPT1006: Expected ')'
aspnetcore-browser-refresh.js (1,18)
```
and
```
SCRIPT1014: Invalid character
browserLink (77,7899)
```

I'm not sure if that's helpful.  IE doesn't give great details about JS errors.  Other browsers are not logging those JS errors, so I'm assuming they are coming from the polyfill.

**Comment by Daddoon** [comment]
Yes i know but i didn't bother about theses exception, because actually, they are related to the BrowserLink / HotReload functionnality of Visual Studio.

So theses JS files support are note mandatory at all, and actually, i imagine they should not load in PRODUCTION environment (at least if everything has been done right on Microsoft side !).

**Comment by SpeednetGroup** [comment]
Ah, OK.  Although looking at aspnetcore-browser-refresh.js it appears that it is the code that reestablishes a link with the server if the connection is dropped.  In the code, I'm noticing some inline functions, which is almost certainly what is triggering IE11.

```
      const action = {
        'UpdateStaticFile': () => updateStaticFile(payload.path),
        'BlazorHotReloadDeltav1': () => applyBlazorDeltas(payload.sharedSecret, payload.deltas),
        'HotReloadDiagnosticsv1': () => displayDiagnostics(payload.diagnostics),
        'BlazorRequestApplyUpdateCapabilities': getBlazorWasmApplyUpdateCapabilities,
        'AspNetCoreHotReloadApplied': () => aspnetCoreHotReloadApplied()
      };
```

**Comment by SpeednetGroup** [comment]
No problem, thanks for your efforts here.  Truly appreciated. 👍

**Comment by Daddoon** [comment]
The methods you mentionned seems, for me, nearly all related to the fast development functionnalities for Visual Studio (Hot reload). Not sure about "UpdateStaticFile" but it may be related too as content on the project may change.

If my memory is correct, Hot reload functionnality improvement has been made by Microsoft in order to prevent to recompile the project everytime something change, and also in order to rapidly see on the screen any Razor page change.

If you have any trouble or something to report, feel free.

I know that there is still an issue while trying to directly upload file through FileInput with the Blazor way, as i suspect the method arrayBuffer(); does not exist on the Blob type on IE11. Some workaround may be possible, but the main issue is that any workaround for this does imply to use some kind of async events, but the original method used in code seems to be a synchronous event. I don't remember if this worked on the .NET 5.0 version.

**Comment by SpeednetGroup** [comment]
I pushed out to a production server, and you're right, those errors disappeared from IE11, so they must be in support of hot reload.  Many thanks.

**Comment by Daddoon** [comment]
Thanks a lot for your review !

**Comment by Daddoon** [comment]
@SpeednetGroup Hi !

Just to say that i have release a new little update.
This only concern the es5module javascript isolation emulation.

https://github.com/Daddoon/Blazor.Polyfill#optional-javascript-isolation--module-import-support

Specially this:

> However due to some context limitation, the \_import\_ may fail if the current app root path you are targeting is not a rooted URL. This mean:
> 
>     This should work by default: https://127.0.0.1/[blazorpage]
>     This should not work by default: https://127.0.0.1/myotherapp/managingsomeurl/[blazorpage]
> 
> In order to workaround this limitation, you may have to compute the relative path by yourself in C# before calling \_import\_, and give it in addition, as a second parameter, the webRootPath. For our second URL example, https://127.0.0.1/myotherapp/managingsomeurl/[blazorpage], this would be instead:
> 
> var module = await js.InvokeAsync<IJSObjectReference>(
>   "\_import\_", "/js/modules/exampleJsInterop.js", "/myotherapp/managingsomeurl/");
> 
> You should find some hint with the NavigationManager.BaseURI service / property.

**Comment by SpeednetGroup** [comment]
Thanks so much for the update!  👍
